on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install PNPM Globally
        run: npm install -g pnpm

      - name: Install Turbo Globally
        run: npm install -g turbo

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      - name: Deploy
        uses: Manishankar13/sixtify-brahma@0.1.0
        with:
          branch: main
          folder: apps/docs/storybook-static
