on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM Globally
        run: npm install -g pnpm

      - name: Install Turbo Globally
        run: npm install -g turbo

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build:web

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy only runs after build completes successfully
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # Use the password secret here
          script: |
            cd /var/sixtify-frontend-dev/sixtify-frontend

            git stash

            git pull

            pnpm install
