name: Deploy to Server

on:
  push:
    branches:
      - main  # or your default branch, e.g., 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust to your Node.js version

      - name: Install dependencies
        run: |
          npm install  # or 'pnpm install' if you're using PNPM

      - name: Build Next.js project
        run: |
          npm run build  # or 'pnpm run build' for PNPM

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /path/to/your/project/on/server
            git pull origin main
            npm install  # or 'pnpm install' for PNPM
            npm run build  # or 'pnpm run build' for PNPM
            npm run start  # or 'pnpm run start' for PNPM
